export const TemplateList = [
    {
        NodeName: '00-住院病案首页',
        FileExtension: null,
        NodePath: '演示文档\\00-住院病案首页',
        FileExists: 2,
        ChildNodes: [
            {
                NodeName: '住院病案首页-云南',
                FileExtension: '.xml',
                NodePath: '演示文档\\00-住院病案首页\\住院病案首页-云南.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '住院病案首页-山东',
                FileExtension: '.xml',
                NodePath: '演示文档\\00-住院病案首页\\住院病案首页-山东.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '住院病案首页-广东',
                FileExtension: '.xml',
                NodePath: '演示文档\\00-住院病案首页\\住院病案首页-广东.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '住院病案首页-河南',
                FileExtension: '.xml',
                NodePath: '演示文档\\00-住院病案首页\\住院病案首页-河南.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '住院病案首页-浙江',
                FileExtension: '.xml',
                NodePath: '演示文档\\00-住院病案首页\\住院病案首页-浙江.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '住院病案首页-湖南',
                FileExtension: '.xml',
                NodePath: '演示文档\\00-住院病案首页\\住院病案首页-湖南.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '住院病案首页-通用版',
                FileExtension: '.xml',
                NodePath: '演示文档\\00-住院病案首页\\住院病案首页-通用版.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '住院病案首页-陕西',
                FileExtension: '.xml',
                NodePath: '演示文档\\00-住院病案首页\\住院病案首页-陕西.xml',
                FileExists: 0,
                ChildNodes: null,
            },
        ],
    },
    {
        NodeName: '01-住院志',
        FileExtension: null,
        NodePath: '演示文档\\01-住院志',
        FileExists: 2,
        ChildNodes: [
            {
                NodeName: '24小时内入出院记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\01-住院志\\24小时内入出院记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '24小时内入院死亡记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\01-住院志\\24小时内入院死亡记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '入院记录(痕迹)',
                FileExtension: '.xml',
                NodePath: '演示文档\\01-住院志\\入院记录(痕迹).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '入院记录--儿科',
                FileExtension: '.xml',
                NodePath: '演示文档\\01-住院志\\入院记录--儿科.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '入院记录--妇科',
                FileExtension: '.xml',
                NodePath: '演示文档\\01-住院志\\入院记录--妇科.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '入院记录--通用',
                FileExtension: '.xml',
                NodePath: '演示文档\\01-住院志\\入院记录--通用.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '入院记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\01-住院志\\入院记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '出院记录-妇科',
                FileExtension: '.xml',
                NodePath: '演示文档\\01-住院志\\出院记录-妇科.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '出院记录-新生儿科',
                FileExtension: '.xml',
                NodePath: '演示文档\\01-住院志\\出院记录-新生儿科.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '出院记录-通用',
                FileExtension: '.xml',
                NodePath: '演示文档\\01-住院志\\出院记录-通用.xml',
                FileExists: 0,
                ChildNodes: null,
            },
        ],
    },
    {
        NodeName: '02-病程记录',
        FileExtension: null,
        NodePath: '演示文档\\02-病程记录',
        FileExists: 2,
        ChildNodes: [
            {
                NodeName: '上级医师查房记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\上级医师查房记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '交班记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\交班记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '会诊记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\会诊记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '出院小结',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\出院小结.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '手术安全核查表',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\手术安全核查表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '手术护理记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\手术护理记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '手术记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\手术记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '手术风险评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\手术风险评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '抢救记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\抢救记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '接班记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\接班记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '日常病程记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\日常病程记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '术前小结',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\术前小结.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '术前讨论记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\术前讨论记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '术后首次病程记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\术后首次病程记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '死亡讨论记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\死亡讨论记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '死亡记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\死亡记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '疑难病例讨论记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\疑难病例讨论记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '转入记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\转入记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '转出记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\转出记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '输血记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\输血记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '阶段小结',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\阶段小结.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '首次病程记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\首次病程记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '麻醉术前访视记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\麻醉术前访视记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '麻醉记录单',
                FileExtension: '.xml',
                NodePath: '演示文档\\02-病程记录\\麻醉记录单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
        ],
    },
    {
        NodeName: '03-护理记录单',
        FileExtension: null,
        NodePath: '演示文档\\03-护理记录单',
        FileExists: 2,
        ChildNodes: [
            {
                NodeName: 'NICU重症监护单',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\NICU重症监护单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '一般护理记录单',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\一般护理记录单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '入院护理记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\入院护理记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '护理记录单(危重)',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\护理记录单(危重).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '护理记录单(手术科室)',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\护理记录单(手术科室).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '护理记录单(神经外科)',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\护理记录单(神经外科).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '护理记录单-录入',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\护理记录单-录入.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '护理记录单',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\护理记录单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '护理记录单2',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\护理记录单2.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '护理记录单3',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\护理记录单3.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '护理记录单4',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\护理记录单4.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '护理记录单5',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\护理记录单5.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '护理记录单6',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\护理记录单6.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '日常护理记录单',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\日常护理记录单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '通用护理记录单',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\通用护理记录单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '麻醉记录单',
                FileExtension: '.xml',
                NodePath: '演示文档\\03-护理记录单\\麻醉记录单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
        ],
    },
    {
        NodeName: '04-检验检查',
        FileExtension: null,
        NodePath: '演示文档\\04-检验检查',
        FileExists: 2,
        ChildNodes: [
            {
                NodeName: 'CT影像诊断报告单',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\CT影像诊断报告单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'CT检查报告单',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\CT检查报告单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'CT检查报告单2',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\CT检查报告单2.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '同视机检查报告',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\同视机检查报告.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '尿液检验申请单',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\尿液检验申请单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '彩色多普勒超声诊断报告单',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\彩色多普勒超声诊断报告单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '微生物培养申请单',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\微生物培养申请单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '急诊科生化、免疫检验申请单',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\急诊科生化、免疫检验申请单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '放射检查报告单',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\放射检查报告单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '检查诊疗报告单-消化系疾病',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\检查诊疗报告单-消化系疾病.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '检验报告单（血常规）',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\检验报告单（血常规）.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '眼部B超检查报告单',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\眼部B超检查报告单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '眼部彩超图文报告',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\眼部彩超图文报告.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '粪便检验申请单',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\粪便检验申请单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '胃镜检查报告单',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\胃镜检查报告单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '超声检查诊断书',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\超声检查诊断书.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '骨髓细胞学检查申请单',
                FileExtension: '.xml',
                NodePath: '演示文档\\04-检验检查\\骨髓细胞学检查申请单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
        ],
    },
    {
        NodeName: '05-评分表',
        FileExtension: null,
        NodePath: '演示文档\\05-评分表',
        FileExists: 2,
        ChildNodes: [
            {
                NodeName: 'ABCD评分',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\ABCD评分.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'Barthel指数评分表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\Barthel指数评分表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'Brunnstrom运动功能评价',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\Brunnstrom运动功能评价.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'CIBIC-PLUS量表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\CIBIC-PLUS量表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'Harris 髋关节功能评分标准',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\Harris 髋关节功能评分标准.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'PD NMS 问卷量表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\PD NMS 问卷量表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'PDQ39评分量表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\PDQ39评分量表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'PD治疗',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\PD治疗.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'UPDRSIII评分量表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\UPDRSIII评分量表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'VAP bundle核查表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\VAP bundle核查表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'WHO儿童生长标准',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\WHO儿童生长标准.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '临床状态评分表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\临床状态评分表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '临床痴呆评定量表(CDR)',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\临床痴呆评定量表(CDR).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '住院患者营养风险筛查（NRS2002）评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\住院患者营养风险筛查（NRS2002）评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '出院归档病历质量评分标准',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\出院归档病历质量评分标准.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '卒中量表(NIHSS)',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\卒中量表(NIHSS).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '压疮评估表（Braden）',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\压疮评估表（Braden）.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '嗅觉评估量表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\嗅觉评估量表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '国际RLS严重程度量表(IRLSSG)',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\国际RLS严重程度量表(IRLSSG).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '多系统萎缩评估量表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\多系统萎缩评估量表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '大科护理质控组活动记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\大科护理质控组活动记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '帕金森病UK脑库临床诊断标准',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\帕金森病UK脑库临床诊断标准.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '帕金森病睡眠量表(PDSS)',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\帕金森病睡眠量表(PDSS).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '帕金森病非运动症状评定量表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\帕金森病非运动症状评定量表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '手术风险评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\手术风险评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '抑郁自评量表(SDS)',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\抑郁自评量表(SDS).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '护理文书质量评分表单',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\护理文书质量评分表单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '护理评估单',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\护理评估单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '日常生活活动能力量表(ADL)1',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\日常生活活动能力量表(ADL)1.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '日常生活活动能力量表(ADL)2',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\日常生活活动能力量表(ADL)2.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '术前_Schwab England评分',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\术前_Schwab England评分.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '术前_UPDRSIII评分',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\术前_UPDRSIII评分.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '术前_急性左旋多巴试验',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\术前_急性左旋多巴试验.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '术后_Schwab England评分',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\术后_Schwab England评分.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '术后_UPDRSIII评分',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\术后_UPDRSIII评分.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '术后_抗帕金森药物使用情况',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\术后_抗帕金森药物使用情况.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '术后_时间试验',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\术后_时间试验.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '术后_满意度评估',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\术后_满意度评估.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '格拉斯哥昏迷评分量表(GCS)',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\格拉斯哥昏迷评分量表(GCS).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '格拉斯哥（GCS）昏迷评分标准',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\格拉斯哥（GCS）昏迷评分标准.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '格拉斯评分',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\格拉斯评分.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '汉密尔顿焦虑量表(HAMA)',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\汉密尔顿焦虑量表(HAMA).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '汉密顿抑郁量表(HAMD)',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\汉密顿抑郁量表(HAMD).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '深静脉导管 Bundle 评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\深静脉导管 Bundle 评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '生活自理能力评估表ADL量表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\生活自理能力评估表ADL量表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '疤痕子宫产前预测改良评分表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\疤痕子宫产前预测改良评分表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '疼痛评分',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\疼痛评分.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '病历评分表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\病历评分表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '病案质量检查记分表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\病案质量检查记分表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '神经内科ABCD2评分神经内科2',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\神经内科ABCD2评分神经内科2.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '神经内科MOCA评分',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\神经内科MOCA评分.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '神经内科NIHSS评分',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\神经内科NIHSS评分.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '科室护理质控小组活动记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\科室护理质控小组活动记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '简明疼痛评估量表（BPI）',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\简明疼痛评估量表（BPI）.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '简易精神状态量表(MMSE)',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\简易精神状态量表(MMSE).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '精细运动能力测定量表（FMFM）',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\精细运动能力测定量表（FMFM）.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '统一帕金森病评定量表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\统一帕金森病评定量表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '统一帕金森病评定量表UPDRS',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\统一帕金森病评定量表UPDRS.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '肌力分级标准（6级法）',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\肌力分级标准（6级法）.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '蒙特利尔认知评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\蒙特利尔认知评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '跌倒、坠床危险因素评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\跌倒、坠床危险因素评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '跌倒、坠床危险因素评估表2',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\跌倒、坠床危险因素评估表2.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '进行性核上性眼肌麻痹量表(PSP)',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\进行性核上性眼肌麻痹量表(PSP).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '阿尔茨海默病评定量表-认知（ADAS-Cog）',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\阿尔茨海默病评定量表-认知（ADAS-Cog）.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '面部表情疼痛量表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\面部表情疼痛量表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '颈椎病临床评价量表',
                FileExtension: '.xml',
                NodePath: '演示文档\\05-评分表\\颈椎病临床评价量表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
        ],
    },
    {
        NodeName: '06-医嘱单',
        FileExtension: null,
        NodePath: '演示文档\\06-医嘱单',
        FileExists: 2,
        ChildNodes: [
            {
                NodeName: '临时医嘱单',
                FileExtension: '.xml',
                NodePath: '演示文档\\06-医嘱单\\临时医嘱单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '长期医嘱单',
                FileExtension: '.xml',
                NodePath: '演示文档\\06-医嘱单\\长期医嘱单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
        ],
    },
    {
        NodeName: '07-知情告知',
        FileExtension: null,
        NodePath: '演示文档\\07-知情告知',
        FileExists: 2,
        ChildNodes: [
            {
                NodeName: '手术知情同意书',
                FileExtension: '.xml',
                NodePath: '演示文档\\07-知情告知\\手术知情同意书.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '授权委托书',
                FileExtension: '.xml',
                NodePath: '演示文档\\07-知情告知\\授权委托书.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '治疗知情同意书-球裹扩张',
                FileExtension: '.xml',
                NodePath: '演示文档\\07-知情告知\\治疗知情同意书-球裹扩张.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '特殊检查-操作安全核查单1',
                FileExtension: '.xml',
                NodePath: '演示文档\\07-知情告知\\特殊检查-操作安全核查单1.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '生育保险特需服务或特殊项目自费同意书',
                FileExtension: '.xml',
                NodePath: '演示文档\\07-知情告知\\生育保险特需服务或特殊项目自费同意书.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '病情告知书',
                FileExtension: '.xml',
                NodePath: '演示文档\\07-知情告知\\病情告知书.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '输血治疗同意书',
                FileExtension: '.xml',
                NodePath: '演示文档\\07-知情告知\\输血治疗同意书.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '麻醉知情同意书',
                FileExtension: '.xml',
                NodePath: '演示文档\\07-知情告知\\麻醉知情同意书.xml',
                FileExists: 0,
                ChildNodes: null,
            },
        ],
    },
    {
        NodeName: '08-临床路径',
        FileExtension: null,
        NodePath: '演示文档\\08-临床路径',
        FileExists: 2,
        ChildNodes: [
            {
                NodeName: '2型糖尿病',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\2型糖尿病.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'Graves',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\Graves.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '不稳定性心绞痛介入治疗',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\不稳定性心绞痛介入治疗.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '儿童室间隔缺损',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\儿童室间隔缺损.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '再生障碍性贫血-1',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\再生障碍性贫血-1.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '再生障碍性贫血-2',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\再生障碍性贫血-2.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '分泌性中耳炎',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\分泌性中耳炎.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '卵巢良性肿瘤',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\卵巢良性肿瘤.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '原发性急性闭角型青光眼',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\原发性急性闭角型青光眼.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '变异记录单',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\变异记录单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '声带息肉',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\声带息肉.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '大肠息肉',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\大肠息肉.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '子宫平滑肌瘤',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\子宫平滑肌瘤.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '急性单纯性阑尾炎',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\急性单纯性阑尾炎.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '急性肾盂肾炎',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\急性肾盂肾炎.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '慢性化脓性中耳炎',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\慢性化脓性中耳炎.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '慢性硬脑膜下血肿',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\慢性硬脑膜下血肿.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '慢性稳定性心绞痛介入治疗',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\慢性稳定性心绞痛介入治疗.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '支原体肺炎',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\支原体肺炎.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '支气管哮喘',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\支气管哮喘.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '支气管扩张',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\支气管扩张.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '支气管肺炎',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\支气管肺炎.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '支气管肺癌',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\支气管肺癌.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '特发性血小板减少性紫癜',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\特发性血小板减少性紫癜.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '狼疮性肾炎行肾穿刺活检',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\狼疮性肾炎行肾穿刺活检.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '短暂性脑缺血发作',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\短暂性脑缺血发作.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '社区获得性肺炎',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\社区获得性肺炎.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '终末期肾脏病常规血液透析治疗',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\终末期肾脏病常规血液透析治疗.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '肋骨骨折合并血气胸',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\肋骨骨折合并血气胸.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '股骨干骨折',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\股骨干骨折.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '股骨颈骨折',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\股骨颈骨折.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '胃十二指肠溃疡',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\胃十二指肠溃疡.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '胆囊结石合并急性胆囊炎',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\胆囊结石合并急性胆囊炎.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '脑梗死',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\脑梗死.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '腹股沟疝',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\腹股沟疝.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '自发性气胸',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\自发性气胸.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '输尿管结石',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\输尿管结石.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '颅骨良性肿瘤',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\颅骨良性肿瘤.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '鼻出血',
                FileExtension: '.xml',
                NodePath: '演示文档\\08-临床路径\\鼻出血.xml',
                FileExists: 0,
                ChildNodes: null,
            },
        ],
    },
    {
        NodeName: '09-门急诊',
        FileExtension: null,
        NodePath: '演示文档\\09-门急诊',
        FileExists: 2,
        ChildNodes: [
            {
                NodeName: '儿科门诊病历',
                FileExtension: '.xml',
                NodePath: '演示文档\\09-门急诊\\儿科门诊病历.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '口腔医学门诊',
                FileExtension: '.xml',
                NodePath: '演示文档\\09-门急诊\\口腔医学门诊.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '急诊入院观察记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\09-门急诊\\急诊入院观察记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '急诊抢救病历',
                FileExtension: '.xml',
                NodePath: '演示文档\\09-门急诊\\急诊抢救病历.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '急诊病历',
                FileExtension: '.xml',
                NodePath: '演示文档\\09-门急诊\\急诊病历.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '急诊病历2',
                FileExtension: '.xml',
                NodePath: '演示文档\\09-门急诊\\急诊病历2.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '急诊记录单',
                FileExtension: '.xml',
                NodePath: '演示文档\\09-门急诊\\急诊记录单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '门诊手术安全核查单',
                FileExtension: '.xml',
                NodePath: '演示文档\\09-门急诊\\门诊手术安全核查单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '门诊病历',
                FileExtension: '.xml',
                NodePath: '演示文档\\09-门急诊\\门诊病历.xml',
                FileExists: 0,
                ChildNodes: null,
            },
        ],
    },
    {
        NodeName: '10-评估单',
        FileExtension: null,
        NodePath: '演示文档\\10-评估单',
        FileExists: 2,
        ChildNodes: [
            {
                NodeName: '14岁以上住院病人营养治疗专业评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\14岁以上住院病人营养治疗专业评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'DM住院病人营养治疗专业评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\DM住院病人营养治疗专业评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'ICU住院病人营养治疗专业评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\ICU住院病人营养治疗专业评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'ICU入院护理评估单',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\ICU入院护理评估单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '产科入院护理评估单',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\产科入院护理评估单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '住院病人自理能力评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\住院病人自理能力评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '儿童住院营养治疗专业评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\儿童住院营养治疗专业评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '儿童入院护理评估单',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\儿童入院护理评估单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '儿童压疮风险再评估单',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\儿童压疮风险再评估单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '儿童跌倒坠床评估单',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\儿童跌倒坠床评估单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '入院护理评估单',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\入院护理评估单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '入院转入评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\入院转入评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '压疮风险再评估单1',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\压疮风险再评估单1.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '康复治疗评估单',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\康复治疗评估单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '急诊病人护理评估单',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\急诊病人护理评估单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '新生儿入院护理评估单',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\新生儿入院护理评估单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '特殊人群评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\特殊人群评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '病情（深静脉穿刺留置拔管指征）评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\病情（深静脉穿刺留置拔管指征）评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '管灌住院病人营养治疗专业评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\管灌住院病人营养治疗专业评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '肾脏住院病人营养治疗专业评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\肾脏住院病人营养治疗专业评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '自理能力评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\自理能力评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '血液净化病人阶段评估表(门诊)',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\血液净化病人阶段评估表(门诊).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '跌倒／坠床再评估单',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\跌倒／坠床再评估单.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '门诊血液净化初始评估表(门诊)',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\门诊血液净化初始评估表(门诊).xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '门诊血液净化初始评估表',
                FileExtension: '.xml',
                NodePath: '演示文档\\10-评估单\\门诊血液净化初始评估表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
        ],
    },
    {
        NodeName: '11-表达式模板',
        FileExtension: null,
        NodePath: '演示文档\\11-表达式模板',
        FileExists: 2,
        ChildNodes: [
            {
                NodeName: 'A表达式介绍',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\A表达式介绍.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'BMI指数表达式版',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\BMI指数表达式版.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'IF表达式',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\IF表达式.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'PDQ39评分量表',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\PDQ39评分量表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: 'XXX中医院住院病案首页',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\XXX中医院住院病案首页.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '中华人民共和国传染病报告卡',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\中华人民共和国传染病报告卡.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '单选框求和与LookUp表达式',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\单选框求和与LookUp表达式.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '可见性表达式表现示例',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\可见性表达式表现示例.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '帕金森病非运动症状评定量表',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\帕金森病非运动症状评定量表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '格拉斯哥昏迷评分量表',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\格拉斯哥昏迷评分量表.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '综合性的单选框_输入域_lookup计算的使用',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\综合性的单选框_输入域_lookup计算的使用.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '西医内科入院记录',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\西医内科入院记录.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '设置某些元素打印功能',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\设置某些元素打印功能.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '输入域与输入域之间的计算',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\输入域与输入域之间的计算.xml',
                FileExists: 0,
                ChildNodes: null,
            },
            {
                NodeName: '门诊血液净化初始评估表(门诊)',
                FileExtension: '.xml',
                NodePath: '演示文档\\11-表达式模板\\门诊血液净化初始评估表(门诊).xml',
                FileExists: 0,
                ChildNodes: null,
            },
        ],
    },
    {
        NodeName: '12-多语言模板',
        FileExtension: null,
        NodePath: '演示文档\\12-多语言模板',
        FileExists: 2,
        ChildNodes: [
            {
                NodeName: '多语言--藏文演示文档',
                FileExtension: '.xml',
                NodePath: '演示文档\\12-多语言模板\\多语言--藏文演示文档.xml',
                FileExists: 0,
                ChildNodes: null,
            },
        ],
    },
];
